[[Darknet]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "18b837b15239bbbcbd06bc376d206a48003d1490"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "cb3f0d954eef0e6e7baf328cb235f61bf40bf778921ff4930d7dd9e01aaa7bc0"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.aarch64-linux-gnu-cxx03.tar.gz"
[[Darknet]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c2a6617da193430e643e0792aa9e074e0d208cc"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "5e1af4412c11193f78ae5e3f6fcd1bb34092ea95b734cd015fecd1b7da75475e"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.aarch64-linux-gnu-cxx11.tar.gz"
[[Darknet]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea14201a67ad9ce8345a2f20d2a39b2fd9b45298"
libc = "musl"
os = "linux"

    [[Darknet.download]]
    sha256 = "e7310ccd5456d89de3fa708460f66032e02aaafc092c22725eb3926cd8d3d3a2"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.aarch64-linux-musl-cxx03.tar.gz"
[[Darknet]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "296fd3633758d04424bc76793ab838ac92a9ae71"
libc = "musl"
os = "linux"

    [[Darknet.download]]
    sha256 = "247951b965f39b65ddc8332985e3676cf6c7c37cc9d6d34c164139547263f4de"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.aarch64-linux-musl-cxx11.tar.gz"
[[Darknet]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c7d82e715df47b308deb4e07e4f278304ddb4866"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "9f3bc76588e8de7104f5c38728fdd09a3ac48005678a240992be0370fcc7e07f"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Darknet]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7115c7bf116ee66c2ff8184806fed51fed0185db"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "7e1cf60f68612dfab1ac9eb607e31a5dd6957caaeaefbd03ccf598fa4b3e088c"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Darknet]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9aa0cb02e788aebde7cd29eb77d35f33fa662d65"
libc = "musl"
os = "linux"

    [[Darknet.download]]
    sha256 = "74086c85b813016afa332d0ac9b02e56c8777fbe3986d0c0ddefd5eb3fa22888"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Darknet]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0aa20a6002847f9392549d887f19c3a604e24cd4"
libc = "musl"
os = "linux"

    [[Darknet.download]]
    sha256 = "a6ee6ede6fe75f3a1f783e67e894646c61303ca3acb1df7dd39e9f7d196b707e"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Darknet]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a516f250f036a437a511a031f5c645f14b4f11d3"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "1b8890c2572da5ac41b0ce857adca5c362dc61c4e55c164d3f04320964c18acc"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.i686-linux-gnu-cxx03.tar.gz"
[[Darknet]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06804b9041c0fbae0e91ab73d3732501d9eaf68a"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "5ffa8e8c9754df24d5594e813e70b3f73767c0e91683a69256390c5fe3845bb8"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.i686-linux-gnu-cxx11.tar.gz"
[[Darknet]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "62a6a74449f7871c0201d3d98f12472c01c1a070"
libc = "musl"
os = "linux"

    [[Darknet.download]]
    sha256 = "e93239a259fcad32da4b9d5e5e146ff4c47e2f9c6efa75331fb9d03c79718ca2"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.i686-linux-musl-cxx03.tar.gz"
[[Darknet]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0eb28b5e443610c36acd749276414e124b5a33bf"
libc = "musl"
os = "linux"

    [[Darknet.download]]
    sha256 = "f50edb2fff681d53cb3cfde989bddbc23dca89f54392ddbddea7b00b2114d84d"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.i686-linux-musl-cxx11.tar.gz"
[[Darknet]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94452cfd0942e4abc7b90536656b88f1c764c6d8"
os = "windows"

    [[Darknet.download]]
    sha256 = "722c47cec799e5431abad4b5166e20fa0a2a159315e5009c58a85335361957ff"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.i686-w64-mingw32-cxx03.tar.gz"
[[Darknet]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1952b4c0e68e4e1fb7512f72e6b0bbc117b720c4"
os = "windows"

    [[Darknet.download]]
    sha256 = "4c1a9a02fa86e75c5b6a366c0857525401035531479880ee8ae2f6c586344a48"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.i686-w64-mingw32-cxx11.tar.gz"
[[Darknet]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5f7eedd25888120afd4d20b0a82bc86a088dff8"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "f89f93867bead33232f40947a9e81df491b1f6cc7049b92ba176ff15c0af694e"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Darknet]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed84aabbd6d71e8f07b481f9273a107c01cfcdb3"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "86f792775d05e29068c923061764452bfa201bc25426518b9887605bac9ee4d8"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Darknet]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "60a86890b2280478eb2070a68db3fab1d42b66e7"
os = "macos"

    [[Darknet.download]]
    sha256 = "796e6be7ca902f83984cb27f07a575dd28114e081077ccd87f69ccc45bbd868b"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.x86_64-apple-darwin14-cxx03.tar.gz"
[[Darknet]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fdf15cdf23c9b5c55fb5fcc1223478d128071c3f"
os = "macos"

    [[Darknet.download]]
    sha256 = "db00aacd4f206c7aa339b2923ef25c25b37014fa194128d41c71b7866d1fa454"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.x86_64-apple-darwin14-cxx11.tar.gz"
[[Darknet]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c584e8342483a2dbead736d538c54d5769027c00"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "b0ca0d874852d7448b10286d2a0859d4760471d245567399c20e8dfd960d397e"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.x86_64-linux-gnu-cxx03.tar.gz"
[[Darknet]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c21f8fa8122885aa5f36786591f824f902024c1"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "f73d2daa0a45abb89e90eb8ef7ebc83aab4a324b867f81d862957f7db895c914"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.x86_64-linux-gnu-cxx11.tar.gz"
[[Darknet]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c93ca3ae29e34b5a8380326fceca855a1969f3fa"
libc = "musl"
os = "linux"

    [[Darknet.download]]
    sha256 = "a55e20caa2292ac625ecd34e143c5f5ae6637865bc41bb83e195b6dd4f64305d"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.x86_64-linux-musl-cxx03.tar.gz"
[[Darknet]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a266f23ca2cf5474be9a04b58f4ca42c3d797d1"
libc = "musl"
os = "linux"

    [[Darknet.download]]
    sha256 = "9b1f9b678505691d2250a7eb984bc216c119c6d0900923b93c618f7b6c233e8b"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.x86_64-linux-musl-cxx11.tar.gz"
[[Darknet]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7ebbc327bbef7bd62561f3df9dd5485c5a507bd"
os = "freebsd"

    [[Darknet.download]]
    sha256 = "90ab09ff2ff8f8cbc9da4443d0f61815e786d167d9063cd4d3132e707dad538b"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[Darknet]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd9b1216b29f894e4206f6d6405c1851ed1d572a"
os = "freebsd"

    [[Darknet.download]]
    sha256 = "119884410fd78c27592feaf645ab07b2ff47bad340b01ba190bb0b653a4c690f"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[Darknet]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "949bffb26f9db7e280c7a27fcf64e246a77ad85d"
os = "windows"

    [[Darknet.download]]
    sha256 = "b44e61c120f8c39fe1675ac06badc51561160e28e764a68c451a0710dda24d78"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[Darknet]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d357d0d84444a187c35e42645dc50112c433aeb1"
os = "windows"

    [[Darknet.download]]
    sha256 = "ad117efbd9e37866d1ee7d284cccaf597b7772c63a2c7d41ee0c83ab89556f50"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2020.6.5+0/Darknet.v2020.6.5.x86_64-w64-mingw32-cxx11.tar.gz"
