[[Darknet]]
arch = "aarch64"
git-tree-sha1 = "8092070395bdcd18d516f4ac084d105d14558251"
os = "macos"

    [[Darknet.download]]
    sha256 = "37df07aae6ace461328017411a8af95baa21899a775bdf07636aa879d97afa1b"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+0/Darknet.v2021.10.29.aarch64-apple-darwin.tar.gz"
[[Darknet]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48f22c13080f925690f47d90270bccf347e703e1"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "44cf5a474da01ba9da1f13bb7d96d6d4ce7082b8f1874e7e88745b1295b0adb4"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+0/Darknet.v2021.10.29.aarch64-linux-gnu-cxx11.tar.gz"
[[Darknet]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b186a81f6a8d1c6a09a3a4fadfd4e9fb30d2341"
libc = "musl"
os = "linux"

    [[Darknet.download]]
    sha256 = "3b49fff3e1c633cb2b70b44c6152dd169fe2030bb8027c2819d096c650f8a5c9"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+0/Darknet.v2021.10.29.aarch64-linux-musl-cxx11.tar.gz"
[[Darknet]]
arch = "aarch64"
git-tree-sha1 = "1fde3813a8fcfa7ff45575a1d444060c673cc85d"
os = "freebsd"

    [[Darknet.download]]
    sha256 = "c06cb138ae5cd3aa27533e5a30bfa077cf6a3a7c30044e7f35ff621312090687"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+0/Darknet.v2021.10.29.aarch64-unknown-freebsd.tar.gz"
[[Darknet]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14e65c3b65b5e3ba7d8e1399f5554862440bf68e"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "e9eb6a7c331b1b5b985ea14401472e435bf7d5497d7d4ab950ed905320768c24"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+0/Darknet.v2021.10.29.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Darknet]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4e8f03aceb2f2f83229626ad55484dcd333a2e0"
libc = "musl"
os = "linux"

    [[Darknet.download]]
    sha256 = "c59227f8cda4325bd52e07aed439067900bb8579ed163c657b48c95e712c0c8a"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+0/Darknet.v2021.10.29.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Darknet]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75d55af16aaa3307ef3a88b0f016c9e500f26db3"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "4a11e9b26960f29e10fc17dbb2101f50d8ddd98d72b6cda41bc589fb5feb24ff"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+0/Darknet.v2021.10.29.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Darknet]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93881fac61ad5a00e7a5d9283bb47f6b5fd9924e"
libc = "musl"
os = "linux"

    [[Darknet.download]]
    sha256 = "bd603e6161bf5f3801a513d2beedcab5c5696a61604f1b008ab8e543821a9828"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+0/Darknet.v2021.10.29.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Darknet]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a38c8ca0305817ee27f5bf5c207df7a6b2d3465"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "08a56591ab881df5ea606cdab611584f638980b2f5185e6d7c6120f9b319a1cb"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+0/Darknet.v2021.10.29.i686-linux-gnu-cxx11.tar.gz"
[[Darknet]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0e593f96cfdd92323c523aaed7132a7cc55d48e"
libc = "musl"
os = "linux"

    [[Darknet.download]]
    sha256 = "9463c893292b04f74ed74e2d5cc33de24e97c19d8d170ce10bcad36fab0e8826"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+0/Darknet.v2021.10.29.i686-linux-musl-cxx11.tar.gz"
[[Darknet]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35a74953ce35210faf82eabd7cdc451527726129"
os = "windows"

    [[Darknet.download]]
    sha256 = "39c2acbf187bd885cdde6051e588c738a8ab3d6b051cd044d1811eb58c0bebf7"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+0/Darknet.v2021.10.29.i686-w64-mingw32-cxx11.tar.gz"
[[Darknet]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d42d182dd424d320ab71353c02da02900093364f"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "53a58ff44a8ccbdaeadd8f1fac66d4ecb966d2196ba1b209d3e33e7b7aec6fa1"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+0/Darknet.v2021.10.29.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Darknet]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1aa9ad51b5c58a3245ccdb091838bbfe729d0319"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "757d8e5055efcd42de1d54bba31c0cec3bc37d5a4d35256e07dceb1e1735a23a"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+0/Darknet.v2021.10.29.riscv64-linux-gnu-cxx11.tar.gz"
[[Darknet]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0823a667d54758e8e62cb6147cdd89aacaa9fec3"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "21b100c90b45396f1596fdd4c68f26a8d0725462b2a28eb50bca932b47877a09"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+0/Darknet.v2021.10.29.x86_64-linux-gnu-cxx11.tar.gz"
[[Darknet]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bed8a947f211739d879d8b8e85df1c4ba934edbe"
libc = "musl"
os = "linux"

    [[Darknet.download]]
    sha256 = "60c94e672142b041776b76e0b805d1d59ce8ea362f633c4c20783e28c5238b63"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+0/Darknet.v2021.10.29.x86_64-linux-musl-cxx11.tar.gz"
[[Darknet]]
arch = "x86_64"
git-tree-sha1 = "a16aa1084f7a2ad5a09ae748d4b8e2465dbc7390"
os = "freebsd"

    [[Darknet.download]]
    sha256 = "9cd8007531fff3f1a3ac364ae7a49b88c89cf543ec51eacb268f9f377b7f6652"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+0/Darknet.v2021.10.29.x86_64-unknown-freebsd.tar.gz"
[[Darknet]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bde316545fd8eda865f98212e13b458772d4239e"
os = "windows"

    [[Darknet.download]]
    sha256 = "9876ec4823d253bdb5d56210bb96e2c6be1908c16f15e0a675514f6ed36ab08d"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+0/Darknet.v2021.10.29.x86_64-w64-mingw32-cxx11.tar.gz"
