[[Darknet]]
arch = "i686"
git-tree-sha1 = "ae1e79f18f2cf04d26c6ef9b8492abd008c39017"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "cf2c609b661368c4af2e8fced3af623f4e755e096c530e50eff4c9bacf83070c"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2019.11.15+1/Darknet.v2019.11.15.i686-linux-gnu.tar.gz"
[[Darknet]]
arch = "x86_64"
git-tree-sha1 = "1308f2ad2975d378367fdaeb2aea0d390d22c312"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "3b4c55391f982f62272f09f31f2154973e7ca89ecc0fb3ae42b1445b0de788c3"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2019.11.15+1/Darknet.v2019.11.15.x86_64-linux-gnu.tar.gz"
[[Darknet]]
arch = "i686"
git-tree-sha1 = "fdf25500c50ccd2dfeff9acfdaa92ab16218dcc1"
os = "windows"

    [[Darknet.download]]
    sha256 = "6fb6e84b3dc5f2e00d9ff8296da6df5c689c4103e7dbb157d0817c98613d180a"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2019.11.15+1/Darknet.v2019.11.15.i686-w64-mingw32.tar.gz"
[[Darknet]]
arch = "x86_64"
git-tree-sha1 = "74a6276902d9b286c526a5b965de5eeefb23c09a"
libc = "musl"
os = "linux"

    [[Darknet.download]]
    sha256 = "15be3871528e4aa84fe31e8da844f77850d5f88eaee13bf2d80ac0acd43a12f7"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2019.11.15+1/Darknet.v2019.11.15.x86_64-linux-musl.tar.gz"
[[Darknet]]
arch = "armv7l"
git-tree-sha1 = "bc681f2bb5b98fa5e6416500d44089a0bfba92b4"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "603cece00cefce692cdd37333d216c538841d5323462fb5b8ba80f1a4d4757fe"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2019.11.15+1/Darknet.v2019.11.15.arm-linux-gnueabihf.tar.gz"
[[Darknet]]
arch = "aarch64"
git-tree-sha1 = "2911f35e7fb2b129d41054be87baada0f59ca909"
libc = "musl"
os = "linux"

    [[Darknet.download]]
    sha256 = "0733f8b0eb92668d9d9ee6b35db7130ca5f825725ce00f8e5fb244615b520506"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2019.11.15+1/Darknet.v2019.11.15.aarch64-linux-musl.tar.gz"
[[Darknet]]
arch = "powerpc64le"
git-tree-sha1 = "737bb2cb1d5ed4615d539ff316f802556de4a9d0"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "4c49dcc136f3118f0c18570719164a27fe866eec45dfb1f0600fb612bb8b66ce"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2019.11.15+1/Darknet.v2019.11.15.powerpc64le-linux-gnu.tar.gz"
[[Darknet]]
arch = "x86_64"
git-tree-sha1 = "521e9c18b10f75960778e8c848a6381071f47d67"
os = "freebsd"

    [[Darknet.download]]
    sha256 = "71549925243572c211821aea4e48a7d6defc85337dbf83d588c3d745e984bc70"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2019.11.15+1/Darknet.v2019.11.15.x86_64-unknown-freebsd11.1.tar.gz"
[[Darknet]]
arch = "aarch64"
git-tree-sha1 = "bc90fae76439b1a29d5046eb74974743d1f065e5"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "a4c5830207ef950790a54ae42f3772f030db74234ff102eb829244f9a9b9a821"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2019.11.15+1/Darknet.v2019.11.15.aarch64-linux-gnu.tar.gz"
[[Darknet]]
arch = "i686"
git-tree-sha1 = "2b7d5c1ade5bf6bc9f9171364732f2fdb69ea5d0"
libc = "musl"
os = "linux"

    [[Darknet.download]]
    sha256 = "97ef902020fb7b7d4ac79024875e58ad9209fb7c7b23a504c476d82af32a9deb"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2019.11.15+1/Darknet.v2019.11.15.i686-linux-musl.tar.gz"
[[Darknet]]
arch = "armv7l"
git-tree-sha1 = "c6c0d3273d6d58bf1e4606fe562516f519db97fe"
libc = "musl"
os = "linux"

    [[Darknet.download]]
    sha256 = "a19c7293fa371d7072dc4db550edb965274dacb4cf9d1a28baaf2a6be4fa4b6d"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2019.11.15+1/Darknet.v2019.11.15.arm-linux-musleabihf.tar.gz"
[[Darknet]]
arch = "x86_64"
git-tree-sha1 = "f58c89d7ef586bfb50158d07252bbb1e45cf5a66"
os = "windows"

    [[Darknet.download]]
    sha256 = "d2d4dbe7b9f124faf11cef4903ab14e159bfa2297a61c20d3786bd63e09e1081"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2019.11.15+1/Darknet.v2019.11.15.x86_64-w64-mingw32.tar.gz"
[[Darknet]]
arch = "x86_64"
git-tree-sha1 = "72fd9b3df6f965f03bc3a91aeb8677dee5a3bcf2"
os = "macos"

    [[Darknet.download]]
    sha256 = "3ba22f119b1717f474340ff809cf522733ab764a65f26e4c8410dfcd9d72e747"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2019.11.15+1/Darknet.v2019.11.15.x86_64-apple-darwin14.tar.gz"
