[[Darknet]]
arch = "aarch64"
git-tree-sha1 = "36338c7dbdbdbd8c36fdba1498bbb493af92d40f"
os = "macos"

    [[Darknet.download]]
    sha256 = "d766617ecb72631089b30ea245723c532955b543e09da121cf8e182dc82286a9"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+1/Darknet.v2021.10.29.aarch64-apple-darwin.tar.gz"
[[Darknet]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cfdb9c9c178586951510325e3341cea021e4803"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "afc94c131de420ea56fab7038a37a4bebc60051e59f23375093cda857c219f49"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+1/Darknet.v2021.10.29.aarch64-linux-gnu-cxx11.tar.gz"
[[Darknet]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0bdb7e53fbc3e7fd05e2e65d56cf1f5180329ffe"
libc = "musl"
os = "linux"

    [[Darknet.download]]
    sha256 = "90eabf46d95115aba99f2f1e792bc7d2abc01a0962b9f50e71a3f4b8d0a68379"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+1/Darknet.v2021.10.29.aarch64-linux-musl-cxx11.tar.gz"
[[Darknet]]
arch = "aarch64"
git-tree-sha1 = "e2d3026114c31821436bd77959a5834af2b4643e"
os = "freebsd"

    [[Darknet.download]]
    sha256 = "9e7369852f3757305014990e633b985e3d9e2382df7c95232789bd49eeffb57f"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+1/Darknet.v2021.10.29.aarch64-unknown-freebsd.tar.gz"
[[Darknet]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df03404e5016fe7c1e0a4306d1482155f0f1004b"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "ecd8319fd559db4f92ed90656a053a4af34e9a9ce93c7a963985da05a83d3133"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+1/Darknet.v2021.10.29.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Darknet]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f12079c177313a09714cf7bcd49c1a1bccccfcda"
libc = "musl"
os = "linux"

    [[Darknet.download]]
    sha256 = "7d5afdff21c432ca1f7f10bc5ba28c2304a8f3a98d28c3ebef767cba9a546023"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+1/Darknet.v2021.10.29.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Darknet]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b2eca34a939812f534920ec15480fa041e9f2c7"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "70bc5f69e949580db4a5c747503b9104b55a0519d50c2eb15fbc1ce7bb2f4445"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+1/Darknet.v2021.10.29.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Darknet]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4698f9376e4a41d558a7d49c7862e45dec623b49"
libc = "musl"
os = "linux"

    [[Darknet.download]]
    sha256 = "6bc52f754856ac73a5602a5b9ff31e715362d6b81e08ce139e6ceaebbfd572e1"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+1/Darknet.v2021.10.29.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Darknet]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "465f0ca00cebd54eb594a85e05b4879bb6a9d3d6"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "90f8822a427db334034fe099d370bf98cb6a95a222d7ef22939eeb14c294a79e"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+1/Darknet.v2021.10.29.i686-linux-gnu-cxx11.tar.gz"
[[Darknet]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb615c1d237c2483c719a5a2b91e5baeb6311f17"
libc = "musl"
os = "linux"

    [[Darknet.download]]
    sha256 = "9113d52e5136bda0a41aa9cf012bbfbe706abf097be76a248498784ff98bc27b"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+1/Darknet.v2021.10.29.i686-linux-musl-cxx11.tar.gz"
[[Darknet]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7afdd79432aed21f8c7a5ed0b47a486817d5ff7"
os = "windows"

    [[Darknet.download]]
    sha256 = "b58b74fbce62e952199a1a713c2d5e687140e5034f66e715d1892fca49f16b56"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+1/Darknet.v2021.10.29.i686-w64-mingw32-cxx11.tar.gz"
[[Darknet]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e840790f762c285d8e65d54cc586fe486e10875c"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "622c59e8ab0b503463d17df848ee25b526b9ce4c5733d890250e25147ef241b8"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+1/Darknet.v2021.10.29.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Darknet]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f60e6b1a428d230037e95dc64eecc5a6e272cfa"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "a552d0bdf6417bb6311c897e584b364998d44851eab0918b66d9ee6cfe93747a"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+1/Darknet.v2021.10.29.riscv64-linux-gnu-cxx11.tar.gz"
[[Darknet]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1aa17393012e8dfa48307927704cdf64cd682a29"
libc = "glibc"
os = "linux"

    [[Darknet.download]]
    sha256 = "e26fbadf5b2ad88b832d0d74c2d1d1e7cdeaa284c33ace22447ebccdcd28ae74"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+1/Darknet.v2021.10.29.x86_64-linux-gnu-cxx11.tar.gz"
[[Darknet]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db85831db893e68e6ce06fdc2f1ddb54b86877d4"
libc = "musl"
os = "linux"

    [[Darknet.download]]
    sha256 = "b98f820c3fb532fdd2b3838ffd569b7dd845827caf5fe1ca6b7894397c91274b"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+1/Darknet.v2021.10.29.x86_64-linux-musl-cxx11.tar.gz"
[[Darknet]]
arch = "x86_64"
git-tree-sha1 = "4a43bc75efa8ab82044043e51c595fdbc6631a49"
os = "freebsd"

    [[Darknet.download]]
    sha256 = "57495eb28225e725730c937d27c6fe0e533ccad0d4b01f12653c228facc56978"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+1/Darknet.v2021.10.29.x86_64-unknown-freebsd.tar.gz"
[[Darknet]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64394af42458bd54fec9c2af2e180bb5fec75031"
os = "windows"

    [[Darknet.download]]
    sha256 = "db79b48becdc20d3db1c1e105fe2d77432de8452f5287306c9d4a2a1b1477b50"
    url = "https://github.com/JuliaBinaryWrappers/Darknet_jll.jl/releases/download/Darknet-v2021.10.29+1/Darknet.v2021.10.29.x86_64-w64-mingw32-cxx11.tar.gz"
